// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> PosprocessTex;
RWTexture2D<float4> DepthTexture;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    PosprocessTex[id.xy] = DepthTexture[id.xy] -PosprocessTex[id.xy];
}
